version: "3"

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    restart: "on-failure"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose:
      - 8000

